version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - API_URL=${API_URL}
      - FRONT_URL=${FRONT_URL}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - RABBIT_URL=${RABBIT_URL}
      - HASH_SALT_ROUNDS=${HASH_SALT_ROUNDS}
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped
    networks:
      - blog-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
