services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - blog-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--loglevel", "warning"]
    restart: unless-stopped
    networks:
      - blog-network

volumes:
  redis-data:

networks:
  blog-network:
    driver: bridge
